services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-frontend
    image: frontend:latest
    container_name: frontend
    ports:
      - "5173:5173"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-backend
    image: backend:latest
    container_name: backend
    ports:
      - "3000:3000"