name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Move to frontend dir
        run: cd frontend
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint