name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: cd frontend && npm ci
      - name: Lint
        run: cd frontend && npm run lint